config/routes.rb
Rails.application.routes.draw do
  resources :subjects
  resources :students
  resources :teachers
  resources :cllasses
  root 'home#index'




end

app/controllers/cllasses_controller.rb
class CllassesController < ApplicationController
  before_action :set_cllass, only: [:show, :edit, :update, :destroy]

  # GET /cllasses
  # GET /cllasses.json
  def index
    @cllasses = Cllass.all
  end

  # GET /cllasses/1
  # GET /cllasses/1.json
  def show
  end

  # GET /cllasses/new
  def new
    @cllass = Cllass.new
  end

  # GET /cllasses/1/edit
  def edit
  end

  # POST /cllasses
  # POST /cllasses.json
  def create
    @cllass = Cllass.new(cllass_params)

    respond_to do |format|
      if @cllass.save
        format.html { redirect_to @cllass, notice: 'Cllass was successfully created.' }
        format.json { render :show, status: :created, location: @cllass }
      else
        format.html { render :new }
        format.json { render json: @cllass.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cllasses/1
  # PATCH/PUT /cllasses/1.json
  def update
    respond_to do |format|
      if @cllass.update(cllass_params)
        format.html { redirect_to @cllass, notice: 'Cllass was successfully updated.' }
        format.json { render :show, status: :ok, location: @cllass }
      else
        format.html { render :edit }
        format.json { render json: @cllass.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cllasses/1
  # DELETE /cllasses/1.json
  def destroy
    @cllass.destroy
    respond_to do |format|
      format.html { redirect_to cllasses_url, notice: 'Cllass was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cllass
      @cllass = Cllass.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cllass_params
      params.require(:cllass).permit(:name)
    end
end

app/helpers/cllasses_helper.rb
module CllassesHelper
end

app/views/cllasses/_form.html.erb
<%= form_with(model: cllass, local: true) do |form| %>
  <% if cllass.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cllass.errors.count, "error") %> prohibited this cllass from being saved:</h2>

      <ul>
      <% cllass.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cllasses/edit.html.erb
<h1>Editing Cllass</h1>

<%= render 'form', cllass: @cllass %>

<%= link_to 'Show', @cllass %> |
<%= link_to 'Back', cllasses_path %>

app/views/cllasses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cllasses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cllasses.each do |cllass| %>
      <tr>
        <td><%= cllass.name %></td>
        <td><%= link_to 'Show', cllass %></td>
        <td><%= link_to 'Edit', edit_cllass_path(cllass) %></td>
        <td><%= link_to 'Destroy', cllass, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cllass', new_cllass_path %>

app/views/cllasses/new.html.erb
<h1>New Cllass</h1>

<%= render 'form', cllass: @cllass %>

<%= link_to 'Back', cllasses_path %>

app/views/cllasses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cllass.name %>
</p>

<%= link_to 'Edit', edit_cllass_path(@cllass) %> |
<%= link_to 'Back', cllasses_path %>